### ISSUE TITLE
api: milestone

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#1175]
This issue keeps track of all the changes which would need to be made as a part of the API refactor milestone
https://miro.com/app/board/uXjVPmmY1Zw=/

**Folder Structure**
- [x] gitcoinco/grants-stack-api#8
- [x] gitcoinco/grants-stack-api#9

**Schema Review**
- [ ] gitcoinco/grants-stack-api#10
  - Round
  - Projects
  - Match
  - Summary

**Votes**
- [x] gitcoinco/grants-stack-api#11
- [x] gitcoinco/grants-stack-api#12
- [x] gitcoinco/grants-round#1179

**Token Price**
- [ ] gitcoinco/grants-stack-api#13
- [ ] gitcoinco/grants-stack-api#14

**API endpoints**
- [ ] gitcoinco/grants-stack-api#15
- [x] gitcoinco/grants-stack-api#16
- [x] gitcoinco/grants-stack-api#17
- [x] gitcoinco/grants-stack-api#18
- [ ] gitcoinco/grants-stack-api#19
 
**Deploy**
- [x] gitcoinco/grants-stack-api#20
- [ ] gitcoinco/grants-stack-api#21

**Comment by bhargavaparoksham** [comment]
@thelostone-mc we need an issue to implement match endpoint to handle other parameters like passport=true, matching_cap=false etc

**Comment by hmrtn** [comment]
Here is my proposal for the directory structure. 

```
grants-round/
├── api/
│   ├── package.json
│   ├── src/
│   │   ├── controllers/
│   │   ├── models/
│   │   ├── handlers/
│   │   ├── routes/
│   │   ├── index.ts
│   ├── tests/
│   │   ├── unit/
│   │   ├── integration/
│   ├── tsconfig.json
├── cache/
│   ├── package.json
│   ├── src/
│   │   ├── cacheService/
│   │   ├── index.ts
│   ├── tests/
│   │   ├── unit/
│   │   ├── integration/
│   ├── tsconfig.json
├── db/
│   ├── package.json
│   ├── src/
│   │   ├── models/
│   │   ├── migrations/
│   │   ├── seeds/
│   │   ├── index.ts
│   ├── tests/
│   │   ├── unit/
│   │   ├── integration/
│   ├── prisma/
│   │   ├── schema.prisma
│   ├── tsconfig.json
..... other packages .....
```

This structure namely moves db and caching outside of the API - which is useful because each of these are a separate service and therefore should be isolated.

**Comment by hmrtn** [comment]
The seeding script in the branch mentioned above can be found here: 

https://github.com/gitcoinco/grants-round/blob/1084--db-votes/packages/api/prisma/seed.ts

Which once run, seeds the tables mentioned above with all data that has been submitted on chain.

**Comment by thelostone-mc** [comment]
Ah is that something we want to pursue at this point in time ? If yes I'll add them in as well
Let's figure this out on today's sync
