### ISSUE TITLE
Builder: update fonts and styles to match designs

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1746]
**Tasks**
- [ ] Project Profile: Make the Project Details font smaller ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![projectdetailsbutton](https://user-images.githubusercontent.com/26017180/191626703-18684442-5a58-4f5b-b816-58461ef158f5.png)

- [x] Project Profile: Header image should be full width, keep the aspect ratio ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![header](https://user-images.githubusercontent.com/26017180/191626712-895ab936-a29e-4d52-aae3-f4dec495f622.png)

- [ ] Project Profile: The font style and sizes for paragraph text and link seem to be different ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A17352))

![detailsparagraph](https://user-images.githubusercontent.com/26017180/191626719-7aaa44e2-4775-4943-b6a4-aca311ae87e4.png)
