### ISSUE TITLE
[Design] Project Search & Discovery Design Requests 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2471]
**Background**
For Project Search & Discovery investments in Grants Stack, we're exploring the following solutions: 

1. **Keyword-based search on projects**. Allow donors to find projects that match or contain certain keywords. 
2. **Browse projects by category**. Allow donors to browse projects by preset categories, i.e. Climate, NFTs, AI, open-source, First-time Grantees, Grants Stack Veterans etc.
3. **Collections Beta** — Select trusted community members off-platform to curate projects in GG19, and display those in the Collections section. 

Based on our Grooming session on 10/18, @gravityblast mentioned that to properly support the above solutions, we would likely want to scope back in an "Explore Projects" tab, where all applications for GG19 will show up, and users will be able to **search for projects, view collections, and browse projects by categories." 

**Tasks** 

- [ ] Add back “Explore Projects” tab on Homepage 
- [ ] Collections → opens up into a new page 
- [ ] Project card → add round label (for projects in many concurrent rounds edge case) 
- [ ] Add a new section on Homepage for Categories 

**Product & Design Links:**
* [Project Search & Discovery PRD](https://www.notion.so/gitcoin/PRD-Project-search-discovery-9f972ebb69174d17ae73f01a7d81bd31?pvs=4)

**Tech Details:**

**Open Questions:**
* What happens when you click "View All" on the Collections or Categories section on the homepage? Where does that take you, the Explore Projects tab with Filters applied? The existing flow Melissa has designed where it opens up within the Home tab? 

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary
