### ISSUE TITLE
Manager: bugs + UI updates epic for Round Edit flow 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2522]
Follow up ticket to: https://github.com/gitcoinco/grants-stack/issues/2374 

DG round on Optimism: 
QF round on Optimism: https://manager.gitcoin.co/#/round/0xa02954613075ea89d6fca6f59168ee67bf9d65d7

Tasks: 

**General**
- [x] (For both QF & DG rounds) Update copy at top of Round Settings tab to [this](https://www.figma.com/file/UIXKYToUBeyb47mVLk7atW/Manager-S19?type=design&node-id=130-2470&mode=design&t=J88ttjbl5U0CsZPn-0)
- [x] When not in edit mode, the text in all fields should be light gray (see the text color of Application Start Date for QF rounds - we want that but for all fields) 

**Round & Application Period tab**
- [x] Update Application End Date to YYYY / MM / DD when in Edit mode (see below for current state) 

<img width="1430" alt="Screen Shot 2023-10-30 at 9 08 28 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/f4aad56e-5dbf-437a-85fd-2645b60313da">

- [x] Past dates text should be light gray (see below for current UI with Round Start Date when it's a date in the past, but the text is black instead of light gray like the Application Start Date) 
<img width="1430" alt="Screen Shot 2023-10-30 at 9 08 28 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/39300443-8f90-4845-98b0-076657b3e024"> 

- [x] For QF rounds, we should be able to check/uncheck rolling applications just like in round setup flow 

- [x] For DG rounds - for rounds that have "No Round End Date", I'm not able to edit the round end date to an earlier date.
