### ISSUE TITLE
[Explorer Redesign] UI and Functionality follow up ticket

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2528]
### Tasks 
**General**
- [x] On the Explore Rounds tab, let's make sure we're only showing rounds that have been marked as public. 

**Explorer Homepage > Home tab > Donate Now section**
- [x] Sort "Donate Now" section by matching pool high to low (show the top 4 rounds with largest matching pools) 
> Rationale: On average, rounds with a low matching pool tend to be spam/test rounds 
- [x] When I click "View all" from the Donate Now section, it should take me to the "Explore Rounds" tab with the status="Active" and type="Quadratic Funding" selected by default 

**Explorer Homepage > Home tab > Rounds Ending Soon section**
- [x] Cap at one row (3 rounds) per Melissa's [designs](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-11219&mode=design&t=2WNEbfBl59Fgp8GQ-0)
- [x] Sort rounds by ending soonest to latest (currently, it's rounds that are ending latest) 
- [x] When I click "View all" from the Rounds Ending Soon section, it should take me to the Explore Rounds tab with sort "Round end earliest" applied 

**Explorer Homepage > Explore Rounds tab** 

Default state of Explore Rounds tab should be (if I just click on the Explore Rounds tab): 
- [ ] Only show Active rounds or rounds Taking Applications by default (the filters status="Active" and status="Taking Applications" should be applied) 
> Rationale: We don't want to load any past rounds (status="Finished") to keep it clean. The option is there for people who want to explore past rounds. 
- [x] Sort by matching pool - high to low

Other minor issues: 
- [x] When I select a filter, I should also be able to unselect it (currently, I can only select a filter and then I'm locked in) 
- [x] I should be able to select multiple filters in the same category, and have them compound (i.e. if I select PGN and Optimism, then I should see all PGN and Optimism rounds) 
- [x] I should be able to select multiple filters across different categories, and have them intersect (i.e. if I select QF and Taking Applications and PGN, then I should only see QF rounds on PGN that are taking applications still) 
- [x] The first time I select a filter, I'm seeing an extra "red check mark" 

<img width="485" alt="Screen Shot 2023-10-31 at 4 24 58 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/3da98553-94fe-48cb-b56a-6b95885dac90">
