### ISSUE TITLE
Explorer: minor bugs on new Explorer Homepage

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2550]
**Summary:** Tracking some minor bugs that I'm seeing on the new Explorer Homepage 

**Tasks**

### Round Filters 
- [x] In the filters on the Explore Rounds tab: seeing testnets and production networks - should only be supported production networks if on production URLs (if on staging, show both testnet and production networks)  
> Supported production networks: Mainnet, Optimism, PGN, Polygon PoS, Fantom, Arbitrum, Avalanche 

<img width="1411" alt="Screen Shot 2023-11-07 at 11 05 31 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/0407f5f8-8f2f-4a4f-a12b-bae672716736">

- [x] When I click on the "Explore Rounds" tab directly, it says that there are no filters (filter = All) and it's showing all rounds, but is only actually showing all active rounds. When I go to this page, I would expect `status = Active` & `status = Taking Applications` to be already checked, so we can filter out rounds that have finished by default 
> Loom: https://www.loom.com/share/762d2c8d31cc4a59868ce02edc54c263

### Defining Active Rounds
Loom (covers below 3 tasks): https://www.loom.com/share/17c15fb479bf4e2a852ad6fb359c0676

- [x] Active Rounds should be rounds that have voting period open -- a.k.a the round has started AND the round has not ended (currently, it looks like we're defining Active Rounds only as rounds that have not ended, which means we're pulling in rounds that have not started as well) 

- [x] For Rounds that have not started yet, let's show copy that says "X days until round starts" based on round start date. Once the round starts, we would show "X days left in round" based on round end date like we currently have. 

- [x] In case this doesn't automatically update, let's make sure the Donate Now section only shows Active Rounds (according to updated definition above) 

### Sorting 
Loom (covers below 3 tasks): https://www.loom.com/share/270b716e733d4000bcf474c6a6b4ef82 

- [x] Sorting by matching pool high to low not sorting accurately (see Loom for more details)

- [x] When I click on Rounds Ending Soon > View All, I'm taken to Explore Rounds tab with `Round end (earliest)` sort applied, and `status = Active`

- [x] Remove "Ending Soon" as a filter 

### Direct Grants Rounds 
Loom (covers below 3 tasks): https://www.loom.com/share/03e9b0f104a540efa78e64f80c8da82e

- [x] DG rounds - says "Ends today" for rounds that have No End Date -- let's show copy "No round end date" instead 

- [x] Remove "match amount" label from Direct Grants round cards 

- [ ] Make sure that all active Direct Grants rounds are shown when the filters `status = Active` and `type = Direct Grants` are selected
