### ISSUE TITLE
[spike] Validate "Managing Operators" milestone data & contract needs

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2719]
**Overview**
We're planning to kick off the "Manage Operators" milestone (being able to add/remove operators from your round) on Wed 12/6, and would like to validate data needs and contract-level constraints ahead of time. 

**Tasks**

- [ ] Review [designs](https://www.figma.com/file/UIXKYToUBeyb47mVLk7atW/Manager-S19?type=design&node-id=130-2470&mode=design&t=AyvWPK8Qrb9VGB6i-0)
- [ ] Answer open questions below 

**Open Questions**
- [ ] Can more than one operator be an admin at the round level? 
- [ ] Can someone be granted a role like "reviewer" where they would just be able to approve/reject applications? Or is there a contract-level constraint? 
- [ ] Can we resolve ENS for the wallet addresses of operators? Like what was recently done for Donation History? 
- [ ] Can we associate a name field with wallet addresses? 
- [ ] Can an operator be added or removed after a round has ended? 
- [ ] What is possible at the contract level if the admin operator's wallet gets compromised? Is there a way to give admin permissions to someone else? Have a backup admin? 
- [ ] What is the best way to handle adding duplicate wallet addresses? What other error states should we account for? 
> Currently, when you add the same wallet address twice when creating a program, it de-duplicates the operator to just one unique operator

**Comment by gravityblast** [comment]
@michellema1208 

When a new round is created, there are some initialization parameters sent directly to the new round contract:
	- the list of admins (taken from the program's admins)
	- the list of operator (taken from the list of the program's operators)
It's not clear to the user that this parameters are sent by default. Shall we show them in the round creation form and make them editable?
It can also be a different issue that we can implement later

**Comment by gravityblast** [comment]
>  Can we associate a name field with wallet addresses?

We could do it but every time a name is added we need to store it somewhere. 
 * in local storage: changing browser would lose the names associated to addresses. these changes are not sync with other admins/operators
 * in the round's metadata: this would require a new transaction to set the new metadata pointer

**Comment by gravityblast** [comment]
>  What is the best way to handle adding duplicate wallet addresses? 

At the contract level addresses cannot be duplicated. In the front-end we can just check if the new address already has the role we are trying to add.

> What other error states should we account for?

Any tx can fail so we need to show the error.
If a user doesn't have the right role for an action, we shouldn't show the action in the UI, so I don't think we need more errors.

**Comment by gravityblast** [comment]
Program roles and Round roles are not coupled.
Removing a role in the program, doesn't remove the same role in the round.

During the creation of a program, the current user is set as the only admin. From the UI the users can only add more Program operators.
