### ISSUE TITLE
DonationVoting Strategy Update Tracker

### ISSUE THREAD

**Issue by 0xKurt** [gitcoinco/grants-stack#2910]
- [x] Make the code changes to `DonationVotingMerkleBase`
- [x] Update versions in config
- [ ] Redeploy strategy to all supported networks
- [ ] Update addresses in `README.md`
PR: https://github.com/allo-protocol/allo-v2/pull/468/files (DO NOT MERGE)

- [x] Update the bytecode in the SDK, bump version & publish -> **version bumped to 1.0.47**
PR: https://github.com/allo-protocol/allo-v2-sdk/pull/39 (Merged)

- [ ] Add the deployed contracts to the `isCloneableStrategy` mapping

- [ ] Update and test createPool and dummy recipient script

**Comment by 0xKurt** [comment]
**Redeploy strategy to all supported networks**

---

**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
  
**Network:**
- DVM-Direct: `0x2f9920e473E30E54bD9D56F571BcebC2470A37B0`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable
  

- DVM-Vault: `0xF567f03CBE158CC2df4f0046AA2c4e99d9A1744a`
    - [ ] Deployed: 
    - [ ] Verified
    - [ ] Clonable

---
