### ISSUE TITLE
DirectGrants Deployment Tracker

### ISSUE THREAD

**Issue by 0xKurt** [gitcoinco/grants-stack#2945]
- [x] Deploy strategy to all supported **testnet** networks 
- [ ] Deploy strategy to all supported **mainnet** networks 

- [ ] Update addresses in `README.md`

- [ ] Update the bytecode in the SDK, bump version & publish -> **version bumped to 1.0.48**
(Draft) PR: https://github.com/allo-protocol/allo-v2-sdk/pull/41

- [ ] Add the deployed contracts to the `isCloneableStrategy` mapping (testnet)
- [ ] Add the deployed contracts to the `isCloneableStrategy` mapping (mainnet)

- [ ] Update and test createPool and dummy recipient script

**New Strategy Ids**
DirectGrants StrategyId: `<ID>`

**Redeploy strategy to all supported networks**

---

**Mumbai:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://mumbai.polygonscan.com/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [x] Verified
    - [ ] Cloneable https://defender.openzeppelin.com/#/admin/contracts/mumbai-0x1133eA7Af70876e64665ecD07C0A0476d09465a1/proposals/1c624e3c-52f7-49f5-a892-71d12244dba4
  
---
  
**Sepolia:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://sepolia.etherscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [x] Verified
    - [ ] Cloneable https://defender.openzeppelin.com/#/admin/contracts/sepolia-0x1133eA7Af70876e64665ecD07C0A0476d09465a1/proposals/ec95fd68-c388-4e66-ae8b-aa7eaeb7b7bc

---
  
**Optimism Goerli:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://goerli-optimism.etherscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [x] Verified
    - [ ] Cloneable https://defender.openzeppelin.com/#/admin/contracts/optimism-goerli-0x1133eA7Af70876e64665ecD07C0A0476d09465a1/proposals/96b063a2-db75-443f-a4a3-89a2418d3157
  
---
  
**Base Goerli:**
~~- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`~~
    - [ ] ~~Deployed: https://goerli.basescan.org/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d~~
    - [ ] ~~Verified~~
    - [ ] ~~Cloneable~~

Base Goerli is not live anymore
  
---
  
**Celo Testnet:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://alfajores.celoscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d#code
    - [x] Verified
    - [ ] Cloneable https://defender.openzeppelin.com/#/admin/contracts/alfajores-0x1133eA7Af70876e64665ecD07C0A0476d09465a1/proposals/6a72c003-2cc9-4f8c-8394-ed88a4d222a3

---
  
**Arbitrum Sepolia:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://sepolia.arbiscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [x] Verified
    - [x] Cloneable 

---
  
**Optimism Sepolia:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [x] Deployed: https://sepolia-optimism.etherscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [x] Verified
    - [x] Cloneable 

---
Mainnets
---
  
**Optimism:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed: https://optimistic.etherscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d#code
    - [ ] Verified
    - [ ] Cloneable 

---
  
**Celo:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed: https://celoscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d#code
    - [ ] Verified
    - [ ] Cloneable 

---
  
**Arbitrum:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed: https://arbiscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [ ] Verified
    - [ ] Cloneable 

---
  
**Base:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed: https://basescan.org/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [ ] Verified
    - [ ] Cloneable 

---
  
**Polygon:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed:  https://polygonscan.com/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [ ] Verified
    - [ ] Cloneable 

---
  
**Ethereum:**
- DirectGrants: `0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d`
    - [ ] Deployed: https://etherscan.io/address/0xaC3f288a7A3efA3D33d9Dd321ad31072915D155d
    - [ ] Verified
    - [ ] Cloneable
