### ISSUE TITLE
Supported Networks for GG20 & Checklist

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-stack#3107]
## Source of Truth for our supported networks going into GG20. The latest Allo contracts will have to be deployed on each supported network.

Note: Since Defender v1 is retiring in less than 90 days we need to also migrate to Defender v2 (possibly prioritize this first).

> We use Defender for managing the deployed contracts with a safe on each network.  

### Networks to add to Defender:
- [x] Scroll
    - [ ] Transfer owner to safe
- [ ] Fantom
    - [ ] Transfer owner to safe
- [x] Avalanche Fuji
    - [ ] Transfer owner to safe

### Funding
- [x] Request funds from DAO for deployments (need to get an estimate for total and we can distribute).

#### Fund Deployer Wallet for Each Network:
- [x] Mainnet
- [x] ~~Optimism~~
- [x] ~~Arbitrum~~
- [x] ~~Polygon~~
- [x] ~~Scroll~~
- [x] ~~Base~~
- [x] ~~Avalanche~~
- [x] ~~Fantom~~

### Grants Stack Networks (supported by Allo):
- Mainnet Networks:
    - [x] Mainnet
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks:
    - [x] Sepolia
    - [x] Optimism Sepolia
    - [x] Arbitrum Sepolia
    - [x] Polygon Mumbai
    - [x] Avalanche Fuji
    - [x] Fantom Testnet

### Strategy deployments:

**Direct Grants**
Address: `0x8564d522b19836b7F5B4324E7Ee8Cb41810E9F9e`
Id: `0x53fb9d3bce0956ca2db5bb1441f5ca23050cb1973b33789e04a5978acfd9ca93`
Version: `v2.1`
- Mainnet
    - [x] Ethereum
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks
     - [x] Sepolia
     - [x] Optimism Sepolia
     - [x] Arbitrum Sepolia
     - [x] Polygon Mumbai
     - [x] Avalanche Fuji
     - [x] Fantom Testnet

**QF Grants**
Address: `0x787eC93Dd71a90563979417879F5a3298389227f`
Id: `0x9fa6890423649187b1f0e8bf4265f0305ce99523c3d11aa36b35a54617bb0ec0`
Version: `v2.1`

- Mainnet
    - [x] Ethereum Mainnet
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks
     - [x] Sepolia
     - [x] Optimism Sepolia
     - [x] Arbitrum Sepolia
     - [x] Polygon Mumbai
     - [x] Avalanche Fuji
     - [x] Fantom Testnet

### Add to cloneable strategies (this is done through Defender):
**Direct Grants**

- Mainnet
    - [x] Ethereum Mainnet
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks
     - [x] Sepolia
     - [x] Optimism Sepolia
     - [x] Arbitrum Sepolia
     - [x] Polygon Mumbai
     - [x] Avalanche Fuji
     - [x] Fantom Testnet
     
**QF Grants**

- Mainnet
    - [x] Ethereum Mainnet
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks
     - [x] Sepolia
     - [x] Optimism Sepolia
     - [x] Arbitrum Sepolia
     - [x] Polygon Mumbai
     - [x] Avalanche Fuji
     - [x] Fantom Testnet

### SDK Updates:
- [x] Add supported networks
- [x] Update ABI's
- [ ] Audited strategies

### Grants Stack
- [x] Update Strategy addresses
- [ ] Update SDK version across apps

### Indexer Updates
- [x] Update indexer to use the new strategies

### Upgrade MRC 
- Mainnet 
    - [x] Mainnet
    - [x] Optimism
    - [x] Arbitrum
    - [x] Polygon
    - [x] Scroll
    - [x] Base
    - [x] Avalanche
    - [x] Fantom
- Test Networks
     - [x] Sepolia
     - [ ] Optimism Sepolia
     - [ ] Arbitrum Sepolia
     - [x] Polygon Mumbai
     - [x] Avalanche Fuji
     - [x] Fantom Testnet
