### ISSUE TITLE
deploy SEI on grants-stack and Allo

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#3225]
**Tasks**
- [x] Update deploy script to support new chain
- [x] Deploy contracts on SEI
- [x] Deploy contracts on MRC
- [x] Update indexer to index new contracts on new chain and token
- [x] Update Builder to support SEI
- [x] Update Round Manager to support SEI
- [x] Update Explorer to support SEI
- [ ] Integrate LIT

Context: https://discord.com/channels/562828676480237578/1219975743446974586 

Fast facts: 
- RPC URL: https://rpc.sei-apis.com/ 
- Token support: SEI, ETH, DAI/USDC to start (both payout and donation voting token, across QF and DG) 
- Docs: https://v2.docs.sei.io/
- Contact: philip@seinetwork.io (also chat with Sov) 

**Details**
- [x] Review above information about SEI to determine project complexity 
- [x] Let Product know if any information is needed that's missing 
- [x] Share an estimated timeline for adding support for SEI 
- [x] Create milestone with starting tickets
