### ISSUE TITLE
Deploy Allo and enable Support on Grants-stack for Celo

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-stack#3273]
**Overview**
Celo team wants to run a round on Celo via Grants Stack. https://docs.google.com/spreadsheets/d/1lwbSi1tBFIufia15i8MEAUgxUxEudAUUc0TJoIveMw4/edit#gid=549909116

**Tasks**
- [x] Update deploy script to support new chain
- [x] Deploy contracts on Celo Mainnet and Testnet
- [x] Deploy MRC on Celo
- [ ] Update indexer to index new contracts on new chain and token
- [ ] Update Builder to support Celo
- [ ] Update Round Manager to support Celo
- [ ] Update Explorer to support Celo
